### ISSUE TITLE
Allow closing the chat buffer with unsaved changes

### ISSUE THREAD

**Issue by annakuzmenkodev** [default-anton/llm-sidekick.nvim#6]
<img width="323" alt="image" src="https://github.com/user-attachments/assets/77f772c1-0ffa-42b4-a035-701a644d504c" />

**Comment by default-anton** [comment]
Done https://github.com/default-anton/llm-sidekick.nvim/commit/1563770ad671a9e0cc6d09db42dc371cf2b48eaa
